# The hyperparameters for all the code should be placed her

# Hyperparameters related to the run
lr: 0.002457
epochs: 80
batch_size: 32
seed: 20
device: cuda:0
save_model: True
path_to_pth_file: /model_pths
n_workers: 8
pin_memory: True
prefetch_factor: 4

#Loss, metrics and scheduler
criterion: focal_loss
pos_weight:  yes
scheduler: none
scheduler_gamma: 0.1
scheduler_step: 20
class_threshold: 0.5
focal_loss_alpha: 0.7
focal_loss_gamma: 2
sched_max_lr: 0.001
weight_decay: 0.001


#dataset
dataset: ptbxl
ptbxl_test_fold: 10
cpsc_test_fold: 8

#otbxl parameters
set: diagnostic
subset: superclass

#ECG hyperparameters
n_leads: 12
ecg_len: 2048
max_ecg_len: 5000
norm: zscore
pre_process: bandpass
data_aug: True
dimensions: 1D

#Model choice hyperparameters
model_type: eegnet
submodel: none
dropout: 0.5
resnet_type: resnet18
reduction: mean

#RNN setup
rnn_layers: 2
rnn_hidden_size: 256
rnn_dropout: 0.1
bidirectional: False

#Transformer setup
enc_dropout: 0.1
num_heads: 4
enc_num_layers: 2
embed_dim: 512
enc_feature_extracture: resnet18
